# Generated by Django 3.0.6 on 2020-05-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name_plural': 'Sessoes'},
        ),
    ]
