# Generated by Django 3.0.6 on 2020-05-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200511_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='slug',
            field=models.SlugField(),
        ),
    ]
