# Generated by Django 3.0.6 on 2020-05-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200511_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='curtidas',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
