# Generated by Django 3.0.6 on 2020-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
