# Generated by Django 3.0.6 on 2020-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200512_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(max_length=512),
        ),
    ]
