# Generated by Django 3.0.6 on 2020-05-12 20:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200512_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
