# Generated by Django 3.0.6 on 2020-05-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_postagem_curtidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.CharField(max_length=512),
        ),
    ]
